stages:
- name: compile
  steps:
  - runScriptConfig:
      image: ccr.ccs.tencentyun.com/jfwang/dotnetcoresdk:3.1
      shellScript: |-
        cd src/NGA/NGA.Producer
        dotnet publish -c Relaase -o publish
        cd ../NGA.Consumer
        dotnet publish -c Relaase -o publish
        cd ../NGA.UI
        dotnet publish -c Relaase -o publish
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: src/NGA/NGA.Producer/Dockerfile
      buildContext: .
      tag: jfwang/nga.producer:1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ccr.ccs.tencentyun.com    
  - publishImageConfig:
      dockerfilePath: src/NGA/NGA.Consumer/Dockerfile
      buildContext: .
      tag: jfwang/nga.consumer:1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ccr.ccs.tencentyun.com
  - publishImageConfig:
      dockerfilePath: src/NGA/NGA.UI/Dockerfile
      buildContext: .
      tag: jfwang/nga.ui:1.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ccr.ccs.tencentyun.com
- name: remove
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -u "token-9xjq9:5dx6wsx5994jvcqlp4gw5wg8s47bdb58pswtbk6k5w92klkb82jcvh" \
        -X DELETE \
        -H 'Accept: application/json' \
        'https://192.168.0.101/v3/project/c-84bcm:p-lplgk/workloads/deployment:nga:ngaproducer' -k
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -u "token-9xjq9:5dx6wsx5994jvcqlp4gw5wg8s47bdb58pswtbk6k5w92klkb82jcvh" \
        -X DELETE \
        -H 'Accept: application/json' \
        'https://192.168.0.101/v3/project/c-84bcm:p-lplgk/workloads/deployment:nga:ngaconsumer' -k
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -u "token-9xjq9:5dx6wsx5994jvcqlp4gw5wg8s47bdb58pswtbk6k5w92klkb82jcvh" \
        -X DELETE \
        -H 'Accept: application/json' \
        'https://192.168.0.101/v3/project/c-84bcm:p-lplgk/workloads/deployment:nga:ngaconsumernew' -k
- name: deploy
  steps:
  - applyYamlConfig:
      path: deployment.yaml
timeout: 60
notification: {}
