---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumer
    managedFields:
    name: ngaconsumer
    namespace: nga
  spec:  
    replicas: 0
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumer
    template:
      metadata:       
        labels:
          workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumer
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SPEED
            value: quickly
          image: ccr.ccs.tencentyun.com/jfwang/nga.consumer:1.${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          name: ngaconsumer
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /etc/localtime
            name: vol1
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: tencent
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: vol1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumernew
    managedFields:
    name: ngaconsumernew
    namespace: nga
  spec:  
    replicas: 2
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumernew
    template:
      metadata:       
        labels:
          workload.user.cattle.io/workloadselector: deployment-nga-ngaconsumernew
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SPEED
            value: quickly
          - name: ConsumerType
            value: New
          image: ccr.ccs.tencentyun.com/jfwang/nga.consumer:1.${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          name: ngaconsumernew
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /etc/localtime
            name: vol1
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: tencent
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: vol1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-nga-ngaproducer
    managedFields:
    name: ngaproducer
    namespace: nga
  spec:  
    replicas: 1
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-nga-ngaproducer
    template:
      metadata:       
        labels:
          workload.user.cattle.io/workloadselector: deployment-nga-ngaproducer
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SPEED
            value: quickly
          image: ccr.ccs.tencentyun.com/jfwang/nga.producer:1.${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          name: ngaproducer
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /etc/localtime
            name: vol1
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: tencent
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: vol1
kind: List
