name: Deploy
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps: 
    - name: SSH into server and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: jfwang.xiaofengyu.com
        port: 8033
        username: jfwang
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        script: |
          export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
          
          cd /volume1/docker/sourcecode 
          git clone https://github.com/jfwangncs/Nga.git
          cd Nga/src/NGA

          jq --arg mysql_conn "${{ secrets.MYSQL_CONNECTIONSTRING }}" \
            --arg rabbitmq_pwd "${{ secrets.RABBITMQ_PASSWORD }}" \
            --arg redis_pwd "${{ secrets.REDIS_PASSWORD }}" \
            '.ConnectionStrings.ConnectionString = $mysql_conn |
              .RabbitMQ.Password = $rabbitmq_pwd |
              .Redis.Password = $redis_pwd' NGA.Consumer/appsettings.Production.json > temp.json && mv temp.json NGA.Consumer/appsettings.Production.json

          jq --arg mysql_conn "${{ secrets.MYSQL_CONNECTIONSTRING }}" \
            --arg rabbitmq_pwd "${{ secrets.RABBITMQ_PASSWORD }}" \
            --arg redis_pwd "${{ secrets.REDIS_PASSWORD }}" \
            '.ConnectionStrings.ConnectionString = $mysql_conn |
              .RabbitMQ.Password = $rabbitmq_pwd |
              .Redis.Password = $redis_pwd' NGA.Producer/appsettings.Production.json > temp.json && mv temp.json NGA.Producer/appsettings.Production.json

          sudo docker build -t jfwangncs/ngap:${{ github.run_number }} -f NGA.Producer/Dockerfile .
          sudo docker build -t jfwangncs/ngac:${{ github.run_number }} -f NGA.Consumer/Dockerfile .
          echo "version: '3'
          services:
             ngac_1:
              image: jfwangncs/ngac:${{ github.run_number }}
              environment:
                - TZ=Asia/Shanghai
                - ASPNETCORE_ENVIRONMENT=Production
              restart: always
             ngp_1:
              image: jfwangncs/ngap:${{ github.run_number }}
              environment:
                - TZ=Asia/Shanghai
                - ASPNETCORE_ENVIRONMENT=Production
                - PRODUCER_PID=-7
              restart: always
             ngp_2:
              image: jfwangncs/ngap:${{ github.run_number }}
              environment:
                - TZ=Asia/Shanghai
                - ASPNETCORE_ENVIRONMENT=Production
                - PRODUCER_PID=-472
              restart: always
          " > /volume1/docker/yaml/nga/compose.yaml
          cd /volume1/docker/yaml/nga
          sudo docker-compose up -d
          rm -r /volume1/docker/sourcecode/Nga
